### ISSUE TITLE
D/NetworkSecurityConfig(14549): No Network Security Config specified, using platform default

### ISSUE THREAD

**Issue by Viktoorrocha** [thyagoluciano/flutter_radio#33]
Bom dia Thyago, ao clicar em um botão para reproduzir meu stream ele retorna essa mensagem.

E/ExoPlayerImplInternal(14549): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://radio.trt11.jus.br:8000/radiotrt11
E/ExoPlayerImplInternal(14549): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
E/ExoPlayerImplInternal(14549): 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
E/ExoPlayerImplInternal(14549): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844)
E/ExoPlayerImplInternal(14549): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
E/ExoPlayerImplInternal(14549): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(14549): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(14549): 	at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal(14549): Caused by: java.net.SocketTimeoutException: SSL handshake timed out
E/ExoPlayerImplInternal(14549): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/ExoPlayerImplInternal(14549): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
E/ExoPlayerImplInternal(14549): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
E/ExoPlayerImplInternal(14549): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
E/ExoPlayerImplInternal(14549): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
E/ExoPlayerImplInternal(14549): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
E/ExoPlayerImplInternal(14549): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
E/ExoPlayerImplInternal(14549): 	... 6 more

**Comment by amsoftpe** [comment]
Add in the manifest:
android:networkSecurityConfig="@xml/network_security_config"
and in the xml file :
`<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">https://radio.trt11.jus.br</domain>
    </domain-config>
</network-security-config>`
