### ISSUE TITLE
Exoplayer2 library throwing InvalidResponseCodeException on a 302 Redirect of http to http url

### ISSUE THREAD

**Issue by JohnBaker123** [thyagoluciano/flutter_radio#46]
Exoplayer2 library throwing InvalidResponseCodeException on a 302 Redirect.

I have a http url that is redirecting to another http url with 302 redirect response.

and this is thrown.

E/ExoPlayerImplInternal( 7283): Source error.
E/ExoPlayerImplInternal( 7283): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302
E/ExoPlayerImplInternal( 7283): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
E/ExoPlayerImplInternal( 7283): 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
E/ExoPlayerImplInternal( 7283): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844)
E/ExoPlayerImplInternal( 7283): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
E/ExoPlayerImplInternal( 7283): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/ExoPlayerImplInternal( 7283): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/ExoPlayerImplInternal( 7283): 	at java.lang.Thread.run(Thread.java:764)

**Comment by devsang31** [comment]
Is there any solution for the above issue?

**Comment by JohnBaker123** [comment]
I had to switch to using a different library. Can't remember which one I used.

**Comment by devsang31** [comment]
Ohk, than I have to find different library to solve the issue.
